### PR TITLE
[1.0] Use the database connection from the config

### LINKED ISSUE #91: Telescope creates migration in the wrong database
## Step To Reproduce

1. Run `php artisan telescope:install`.
2. Change `storage` => `database` => `connection` in `telescope.php` to another (`sqlite` as example).
3. Run `php artisan migrate`.

## Expected

Сreating a structure within the specified connection.

## Actual

Creating migrations on the primary connection.

### PR DESCRIPTION
**Pull request by simonellensohn**
The migrations are executed on the default DB connection instead of the one provided in the telescope config file.

Fixes #91

### CODE REVIEW

File: src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php [hunk 1]
```diff
@@ -6,14 +6,31 @@
...
+
     /**
      * Run the migrations.
      *
      * @return void
      */
     public function up()
     {
-        Schema::create('telescope_entries', function (Blueprint $table) {
+        Schema::connection($this->connection)->create('telescope_entries', function (Blueprint $table) {
```
Comment (lucasmichot) [inline src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php]: Maybe simply create a variable for `Schema::connection($this->connection)` in the constructor
